name: test_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - cfgrib
  - pygrib
  - s3fs
  - pytest-cov
  - ujson
  - python-blosc
  - pip
  - kerchunk
  - jupyter
  - pip:
      - git+https://github.com/fsspec/filesystem_spec
